import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { getCurrentUser } from "@/lib/auth";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Green Office System",
  description: "Generated by create next app. Hosted on Amazon EC2 instance (ubuntu)",
  icons: {
      icon: "images/icons/green-office-formatted.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="flex p-8 bg-gray-50"> 
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
